Kickoff api
ivoguzman23/WBookApi_Training_Ivo pull request #4
Opened 2021-06-18 20:02 UTC by ivoguzman23

## Summary

Rubocop and CircleCI installation and configuration

This was an old card but I had problems, now is working fine.
Rubocop, Rubocop-rails gem installation, CircleCI project configuration.

## Screenshots

![image](https://user-images.githubusercontent.com/85500573/122610852-ae999e00-d056-11eb-8868-92bf64477f34.png)

![image](https://user-images.githubusercontent.com/85500573/122610900-c2450480-d056-11eb-87b6-9c770c3de864.png)

## TRELLO Card

https://trello.com/c/DeWRiBNT/13-configurar-circleci-o-si-no-travisci

2021-06-19 00:16 UTC, lucasenriquez requested changes

2021-06-19 00:16 UTC, lucasenriquez commented on .circleci/config.yml
> +      - build
Add a newline at the end of the file

2021-06-19 00:16 UTC, lucasenriquez commented on .env
> +DEVISE_JWT_SECRET_KEY=44a238d54045d8fe4a9a9cf3fd5a530ebb77d6122aff436d212917c65919ccda9e106ee1cbcd335232924657288c406433d80d3ed4aa3c8d675664d115421e00
This file should not be here

2021-06-19 00:16 UTC, lucasenriquez commented on .rubocop.yml
> +  Enabled: false
Add a newline at the end of the file

2021-06-19 00:16 UTC, lucasenriquez commented on Gemfile
> +gem 'therubyracer'
Add a newline at the end of the file

2021-06-22 13:36 UTC, melissaregnier requested changes

2021-06-22 13:36 UTC, melissaregnier commented on app/controllers/application_controller.rb
> +      validation_error(resource)
This can be made simpler with an early return and an inline `if`.

2021-06-22 16:43 UTC, melissaregnier requested changes

2021-06-22 16:43 UTC, melissaregnier commented on app/controllers/application_controller.rb
> +    #SE detiene el codigo en el return
this comment is not needed

2021-06-22 16:43 UTC, melissaregnier commented on app/controllers/application_controller.rb
> +    return render json: resource if resource.errors.empty?
add an empty line after an early return

2021-06-23 18:10 UTC, merged