Rent model
ivoguzman23/WBookApi_Training_Ivo pull request #9
Opened 2021-06-25 14:36 UTC by ivoguzman23

## Summary

Add test for rent and user models

I made the rspec tests and I use the factories for it.

## Screenshots

## TRELLO Card

https://trello.com/c/tE1n77g0/42-crear-tests-para-el-modelo-de-rent-y-user

2021-06-25 16:25 UTC, lucasenriquez requested changes

2021-06-25 16:25 UTC, lucasenriquez commented on spec/models/book_test_spec.rb
> +  let(:genre)            { Faker::Lorem.word}
You can use factories here

2021-06-25 16:25 UTC, lucasenriquez commented on spec/factories/users.rb
> +end
Add a newline at the end of the file

2021-06-25 16:25 UTC, lucasenriquez commented on spec/models/user_test_spec.rb
> +end
Add a newline at the end of the file

2021-06-25 16:25 UTC, lucasenriquez commented on spec/support/factory_bot.rb
> +
Add a newline at the end of the file

2021-06-28 18:10 UTC, lucasenriquez approved these changes

2021-07-01 18:38 UTC, GabrielPiccini approved these changes

2021-07-13 13:43 UTC, merged